language: ruby
cache: bundler
bundler_args: --without development
rvm:
  - "2.2"
env:
  - DB=postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake spec
  - bundle exec rubocop -R --config .rubocop.yml --fail-level error
